// OSN 2024 SD Nasional Teori1 Q14 — graph-colouring polygon-tile figure.
// Source: docs/reference/ocr-res/osn/nasional/sd/2024-teori1.imgs/007.jpg
// Figure: 8 pentagons (segi lima) in two 2×2 groups (each a C4 cycle) + 1 quadrilateral (segi empat).
// Pentagon palette: {merah, kuning, biru}. Quadrilateral palette: {hijau, ungu}.
// Adjacent shapes must have different colours. Cross-type pairs are always OK (disjoint palettes).
// Valid colourings: P(C4,3)² × 2 = 18 × 18 × 2 = 648.
// No existing primitive covers polygon-tile figures — bespoke SVG below.

// ── Geometry helpers ───────────────────────────────────────────────────────────
// Each 2×2 block of 4 pentagons is generated by cutting one outer corner of each cell.
// x0,y0 = top-left origin; CW = cell width; CH = cell height; N = notch size.
// Result: 4 pentagons forming a C4 adjacency cycle.

function blockPoints(x0: number, y0: number, CW = 80, CH = 60, N = 14) {
  const x1 = x0 + CW,  x2 = x0 + 2 * CW
  const y1 = y0 + CH,  y2 = y0 + 2 * CH
  return {
    // TL — notch at top-left corner
    P1: `${x0+N},${y0} ${x1},${y0} ${x1},${y1} ${x0},${y1} ${x0},${y0+N}`,
    // TR — notch at top-right corner
    P2: `${x1},${y0} ${x2-N},${y0} ${x2},${y0+N} ${x2},${y1} ${x1},${y1}`,
    // BL — notch at bottom-left corner
    P3: `${x0},${y1} ${x1},${y1} ${x1},${y2} ${x0+N},${y2} ${x0},${y2-N}`,
    // BR — notch at bottom-right corner
    P4: `${x1},${y1} ${x2},${y1} ${x2},${y2-N} ${x2-N},${y2} ${x1},${y2}`,
  }
}

// ── Colour palette ─────────────────────────────────────────────────────────────
export const PENT_FILL   = '#DBEAFE' // blue-100  — uncoloured pentagon
export const PENT_STROKE = '#1D4ED8' // blue-700
export const QUAD_FILL   = '#FEF9C3' // yellow-100 — uncoloured quadrilateral
export const QUAD_STROKE = '#A16207' // yellow-700

// Highlight fills used by the explainer
export const HIGH_PENT  = '#93C5FD' // blue-300
export const HIGH_QUAD  = '#FDE68A' // amber-200
export const DONE_GREEN = '#86EFAC' // green-300

// ── Shared figure props ────────────────────────────────────────────────────────
export interface ColorTileFigureProps {
  /** Which shape ids to highlight: 'p1'–'p8' and/or 'q' */
  highlight?: string[]
  /** Colour fill override map: shape-id → CSS colour string */
  colorMap?: Partial<Record<string, string>>
}

const TOP = blockPoints(20, 10)
const BOT = blockPoints(20, 155)
const QUAD_PTS = '20,130 180,130 180,155 20,155'

/** Shared tile figure — default state is uncoloured (problem view). */
export function ColorTileFigure({ highlight = [], colorMap = {} }: ColorTileFigureProps) {
  function pentFill(id: string) {
    if (colorMap[id]) return colorMap[id]!
    if (highlight.includes(id)) return HIGH_PENT
    return PENT_FILL
  }
  function quadFill() {
    if (colorMap['q']) return colorMap['q']!
    if (highlight.includes('q')) return HIGH_QUAD
    return QUAD_FILL
  }

  const common = { strokeWidth: 2, strokeLinejoin: 'round' as const }
  const pStroke = { stroke: PENT_STROKE, ...common }
  const qStroke = { stroke: QUAD_STROKE, ...common }

  return (
    <svg
      viewBox="0 0 200 280"
      xmlns="http://www.w3.org/2000/svg"
      className="w-full max-w-[240px] mx-auto"
    >
      {/* ── Top group: P1–P4 (C4 cycle) ── */}
      <polygon points={TOP.P1} fill={pentFill('p1')} {...pStroke} />
      <polygon points={TOP.P2} fill={pentFill('p2')} {...pStroke} />
      <polygon points={TOP.P3} fill={pentFill('p3')} {...pStroke} />
      <polygon points={TOP.P4} fill={pentFill('p4')} {...pStroke} />

      {/* ── Quadrilateral (segi empat) ── */}
      <polygon points={QUAD_PTS} fill={quadFill()} {...qStroke} />

      {/* ── Bottom group: P5–P8 (C4 cycle) ── */}
      <polygon points={BOT.P1} fill={pentFill('p5')} {...pStroke} />
      <polygon points={BOT.P2} fill={pentFill('p6')} {...pStroke} />
      <polygon points={BOT.P3} fill={pentFill('p7')} {...pStroke} />
      <polygon points={BOT.P4} fill={pentFill('p8')} {...pStroke} />

      {/* ── Shape-type labels (small, centred) ── */}
      {[
        { id: 'p1', cx: 60,  cy: 40  },
        { id: 'p2', cx: 140, cy: 40  },
        { id: 'p3', cx: 60,  cy: 100 },
        { id: 'p4', cx: 140, cy: 100 },
        { id: 'p5', cx: 60,  cy: 185 },
        { id: 'p6', cx: 140, cy: 185 },
        { id: 'p7', cx: 60,  cy: 245 },
        { id: 'p8', cx: 140, cy: 245 },
      ].map(({ id, cx, cy }) => (
        <text
          key={id}
          x={cx} y={cy + 5}
          textAnchor="middle"
          fontSize="13"
          fontWeight="700"
          fill={PENT_STROKE}
          fontFamily="sans-serif"
        >5</text>
      ))}
      <text x="100" y="147" textAnchor="middle" fontSize="13" fontWeight="700" fill={QUAD_STROKE} fontFamily="sans-serif">4</text>
    </svg>
  )
}

// ── Default export: stem illustration (no colour, no answer) ─────────────────
export default function ColorTileOSN24NT1Q14Illustration() {
  return <ColorTileFigure />
}
