/**
 * Generates src/components/wmi/PastPapers/WMI/INDEX.md — a searchable catalog
 * of every illustration / explainer / option renderer wired in registry.ts.
 *
 * Purpose: "reuse before you build". Before authoring a new visual, grep this
 * index for keywords (clock, balance, kenken, rolling, fraction, ...) and point
 * the registry at an existing component instead of recreating it.
 *
 * Usage: npm run wmi:index   (re-run after every Phase 4 wiring pass)
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import { buildPoolOutputs, type PoolEntry } from './poolCatalog.js'

const DIR = join('src', 'components', 'wmi', 'PastPapers', 'WMI')
const REGISTRY = join(DIR, 'registry.ts')
const OUT = join(DIR, 'INDEX.md')

const src = readFileSync(REGISTRY, 'utf8')

// --- imports: component name -> module file ---
const importFile = new Map<string, string>()
for (const m of src.matchAll(/import\s+(\w+)\s+from\s+'\.\/([\w./-]+)'/g)) {
  importFile.set(m[1], m[2])
}
for (const m of src.matchAll(/import\s*\{([^}]+)\}\s*from\s+'\.\/([\w./-]+)'/g)) {
  for (const name of m[1].split(',').map((s) => s.trim()).filter(Boolean)) {
    importFile.set(name, m[2])
  }
}

// --- VISUALS entries ---
interface Usage { code: string; role: 'Illustration' | 'Explainer' | 'ChoiceRenderer' }
const usages = new Map<string, Usage[]>() // component -> usages
function addUsage(comp: string, code: string, role: Usage['role']) {
  if (!usages.has(comp)) usages.set(comp, [])
  usages.get(comp)!.push({ code, role })
}
for (const m of src.matchAll(/'([A-Z0-9]+-[A-Z0-9]+-Q\d+)':\s*\{([^}]*)\}/g)) {
  const code = m[1]
  const ill = m[2].match(/Illustration:\s*(\w+)/)
  const exp = m[2].match(/Explainer:\s*(\w+)/)
  if (ill) addUsage(ill[1], code, 'Illustration')
  if (exp) addUsage(exp[1], code, 'Explainer')
}
const crBlock = src.match(/CHOICE_RENDERERS[^=]*=\s*\{([\s\S]*?)\n\}/)
if (crBlock) {
  for (const m of crBlock[1].matchAll(/'([A-Z0-9]+-[A-Z0-9]+-Q\d+)':\s*(\w+)/g)) {
    addUsage(m[2], m[1], 'ChoiceRenderer')
  }
}

// --- per-file metadata: header comment + aria-labels + keywords ---
function fileMeta(file: string): { desc: string; keywords: string } {
  const candidates = [join(DIR, `${file}.tsx`), join(DIR, `${file}.ts`)]
  const path = candidates.find((p) => existsSync(p))
  let desc = ''
  if (path) {
    const text = readFileSync(path, 'utf8')
    const header = text.match(/^\s*\/\*\*?([\s\S]*?)\*\//)
    if (header) {
      desc = header[1].replace(/^\s*\*\s?/gm, ' ').replace(/\s+/g, ' ').trim()
    } else {
      const lines = text.split(/\r?\n/).filter((l) => l.startsWith('//'))
      if (lines.length) desc = lines.slice(0, 3).map((l) => l.replace(/^\/\/\s?/, '')).join(' ')
    }
    if (!desc) {
      const aria = text.match(/aria-label=\{?["'`]([^"'`]{10,160})/) || text.match(/ariaLabel\s*[:=]\s*["'`]([^"'`]{10,160})/)
      if (aria) desc = aria[1]
    }
  }
  const keywords = file
    .split('/')
    .pop()!
    .replace(/(Illustration|Explainer|Option|Visual|Steps)$/g, '')
    .replace(/([a-z0-9])([A-Z])/g, '$1 $2')
    .toLowerCase()
  return { desc: desc.slice(0, 220), keywords }
}

// --- group by module file ---
const byFile = new Map<string, { components: Map<string, Usage[]> }>()
for (const [comp, us] of usages) {
  const file = importFile.get(comp)
  if (!file) continue
  if (!byFile.has(file)) byFile.set(file, { components: new Map() })
  byFile.get(file)!.components.set(comp, us)
}

const lines: string[] = [
  '# Paper-question visual index',
  '',
  '<!-- GENERATED by `npm run wmi:index` — do not edit by hand. -->',
  '',
  'Searchable catalog of every component wired in `registry.ts`. Before building a',
  'new illustration/explainer/option renderer, grep here for keywords; if a match',
  'covers the same puzzle, point the registry at it instead (reuse-before-build).',
  'A component listed under several codes is already shared across papers.',
  '',
  '| File | Keywords | Exports → used by | Description |',
  '|---|---|---|---|',
]

const sorted = [...byFile.entries()].sort(([a], [b]) => a.localeCompare(b))
for (const [file, { components }] of sorted) {
  const { desc, keywords } = fileMeta(file)
  const exports = [...components.entries()]
    .map(([comp, us]) => {
      const codes = us.map((u) => `${u.code} (${u.role[0]})`).join(', ')
      return `**${comp}**: ${codes}`
    })
    .join('<br>')
  lines.push(`| \`${file}\` | ${keywords} | ${exports} | ${desc.replace(/\|/g, '\\|')} |`)
}

lines.push(
  '',
  `Roles: (I) Illustration, (E) Explainer, (C) ChoiceRenderer. ${usages.size} components in ${byFile.size} files.`,
  '',
)

writeFileSync(OUT, lines.join('\n'), 'utf8')
console.log(`wrote ${OUT}: ${usages.size} components, ${byFile.size} files`)

// --- pool catalog (EXPLAINER_POOL.md + pool.json) ---
const POOL_MD = join(DIR, 'EXPLAINER_POOL.md')
const POOL_JSON = join(DIR, 'pool.json')

const poolEntries: PoolEntry[] = []
for (const [file, { components }] of sorted) {
  const usedBy = [...new Set([...components.values()].flat().map((u) => u.code))].sort()
  const compNames = [...components.keys()]
  const illName = compNames.find((c) => /Illustration$/.test(c)) ?? compNames[0]
  const tsxPath = join(DIR, `${file}.tsx`)
  let entry: PoolEntry | null = null
  // Only dynamic-import files that opt in via definePoolMeta() — cheap + precise.
  if (existsSync(tsxPath) && /definePoolMeta\s*\(/.test(readFileSync(tsxPath, 'utf8'))) {
    try {
      const mod = await import(pathToFileURL(tsxPath).href)
      const meta = mod.meta ?? mod.default?.meta
      if (meta?.id) {
        entry = {
          id: meta.id,
          file,
          title: meta.title,
          summary: meta.summary,
          useWhen: meta.useWhen,
          tags: meta.tags ?? [],
          grades: meta.grades ?? [],
          status: meta.status ?? 'bespoke',
          paramsExample: meta.paramsExample,
          usedBy,
        }
      }
    } catch (err) {
      console.warn(`pool: could not import meta from ${file}: ${(err as Error).message}`)
    }
  }
  if (!entry) {
    const { desc, keywords } = fileMeta(file)
    entry = {
      id: keywords.replace(/\s+/g, '-') || file.toLowerCase(),
      file,
      title: illName ?? file,
      summary: desc || '(no description)',
      useWhen: '',
      tags: keywords.split(/\s+/).filter(Boolean),
      grades: [],
      status: 'bespoke',
      usedBy,
    }
  }
  poolEntries.push(entry)
}

const { md: poolMd, json: poolJson } = buildPoolOutputs(poolEntries)
writeFileSync(POOL_MD, poolMd, 'utf8')
writeFileSync(POOL_JSON, poolJson, 'utf8')
console.log(
  `wrote ${POOL_MD} + ${POOL_JSON}: ${poolEntries.length} entries (${poolEntries.filter((e) => e.status === 'template').length} templates)`,
)
