/**
 * Pure assembly of the explainer-pool catalog outputs (EXPLAINER_POOL.md + pool.json)
 * from per-component pool entries. No filesystem access — unit-testable.
 * Consumed by build-visual-index.ts.
 */
export interface PoolEntry {
  id: string
  file: string
  title: string
  summary: string
  useWhen: string
  tags: string[]
  grades: number[]
  status: 'template' | 'bespoke'
  paramsExample?: string
  usedBy: string[]
}

export function buildPoolOutputs(entries: PoolEntry[]): { md: string; json: string } {
  const templates = entries
    .filter((e) => e.status === 'template')
    .sort((a, b) => a.id.localeCompare(b.id))
  const bespoke = entries.filter((e) => e.status === 'bespoke')

  const lines: string[] = [
    '# Explainer pool catalog',
    '',
    '<!-- GENERATED by `npm run wmi:index` — do not edit by hand. -->',
    '',
    'Read this FIRST when converting a paper question that needs a visual.',
    'Prefer a TEMPLATE (true reuse: set `visual.templateId` + `params`, no new file).',
    'Otherwise copy-adapt the closest bespoke entry. Build new only if nothing fits',
    '(and give the new pair a `meta` block so it lands here).',
    '',
    '## Templates',
    '',
  ]
  if (templates.length === 0) lines.push('_(none yet)_', '')
  for (const t of templates) {
    lines.push(`### \`${t.id}\` — ${t.title}`)
    lines.push(`- file: \`${t.file}\`  · grades ${t.grades.join(',')} · tags: ${t.tags.join(', ')}`)
    lines.push(`- summary: ${t.summary}`)
    lines.push(`- use when: ${t.useWhen}`)
    if (t.paramsExample) lines.push('- params example: `' + t.paramsExample + '`')
    if (t.usedBy.length) lines.push(`- used by: ${t.usedBy.join(', ')}`)
    lines.push('')
  }

  lines.push('## Bespoke (copy-adapt)', '')
  const byTag = new Map<string, PoolEntry[]>()
  for (const e of bespoke) {
    const tag = e.tags[0] ?? 'untagged'
    if (!byTag.has(tag)) byTag.set(tag, [])
    byTag.get(tag)!.push(e)
  }
  for (const tag of [...byTag.keys()].sort()) {
    lines.push(`**${tag}**  `)
    for (const e of byTag.get(tag)!.sort((a, b) => a.id.localeCompare(b.id))) {
      const used = e.usedBy.length ? ` _[${e.usedBy.join(', ')}]_` : ''
      lines.push(`- \`${e.id}\` (${e.file}) — ${e.summary}${used}`)
    }
    lines.push('')
  }

  return { md: lines.join('\n'), json: JSON.stringify(entries, null, 2) }
}
