/**
 * Promotion-candidate report: which bespoke shapes recur enough to deserve a
 * parameterized template? Reads pool.json (generated by wmi:index) and clusters
 * bespoke entries by their primary tag, skipping tags a template already covers.
 *
 * Usage: npm run wmi:pool-candidates
 */
import { readFileSync } from 'node:fs'
import { join } from 'node:path'
import { pathToFileURL } from 'node:url'
import type { PoolEntry } from './poolCatalog.js'

export interface Cluster {
  tag: string
  count: number
  ids: string[]
}

export function clusterBespoke(entries: PoolEntry[], minCount = 3): Cluster[] {
  const templateTags = new Set(
    entries.filter((e) => e.status === 'template').flatMap((e) => e.tags),
  )
  const byTag = new Map<string, string[]>()
  for (const e of entries) {
    if (e.status !== 'bespoke') continue
    const tag = e.tags[0] ?? 'untagged'
    if (!byTag.has(tag)) byTag.set(tag, [])
    byTag.get(tag)!.push(e.id)
  }
  const clusters: Cluster[] = []
  for (const [tag, ids] of byTag) {
    if (ids.length >= minCount && !templateTags.has(tag)) clusters.push({ tag, count: ids.length, ids })
  }
  return clusters.sort((a, b) => b.count - a.count || a.tag.localeCompare(b.tag))
}

// Run as a script (not when imported by tests).
if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const poolPath = join('src', 'components', 'wmi', 'PastPapers', 'WMI', 'pool.json')
  const entries = JSON.parse(readFileSync(poolPath, 'utf8')) as PoolEntry[]
  const clusters = clusterBespoke(entries)
  if (clusters.length === 0) {
    console.log('No promotion candidates (no untemplated tag has ≥3 bespoke entries).')
  } else {
    console.log('Promotion candidates — untemplated shapes recurring ≥3 times:\n')
    for (const c of clusters) {
      console.log(`  ${c.tag}  (${c.count})  e.g. ${c.ids.slice(0, 5).join(', ')}${c.ids.length > 5 ? ', …' : ''}`)
    }
  }
}
