// api/services/gamification/index.ts
//
// Gamification orchestrator. Called from `submitVideoScore` INSIDE the
// same withTransaction block (decision E1 from the eng review).
//
// Plan 1 scope: handle quiz completion + score improvement events, append
// XP to the reward ledger, and update the cached profile. Quest and
// achievement evaluators ship in Plans 2 and 3.
//
// XP values (Plan 1, hard-coded — Plan 6 admin tuning will move these to
// quest/achievement template tables):
//   - QUIZ_COMPLETION_XP    : 25 per first-time submission
//   - SCORE_IMPROVED_XP     : 10 when a correction beats prior best
//   - HIGH_SCORE_XP         : 15 when score >= 80% (first-time only)
//   - PERFECT_SCORE_XP      : 25 when score == 100% (first-time only)
//
// Idempotency: every ledger and event row carries a UNIQUE key on the
// score_attempt id, so HTTP retries can't double-grant.

import type { PoolClient } from 'pg'
import { emitEvent, type EventType } from './events.js'
import { appendLedger } from './ledger.js'
import { updateProfileWithDelta, type ProfileSnapshot } from './profileUpdater.js'
import type { LevelTier } from './levelCurve.js'
import { ensureTodaysQuests } from './questGenerator.js'
import { evaluateForEvent, type QuestProgressResult } from './questEvaluator.js'
import { updateStreakForActivity, type StreakState } from './streakUpdater.js'
import {
  evaluateAchievements,
  type UnlockedAchievement,
} from './achievementEvaluator.js'

export interface ProcessScoreInput {
  childId: string
  scoreAttemptId: string
  videoId: string
  videoSubjectId: string | null
  correctAnswers: number
  totalQuestions: number
  scorePercentage: number     // 0-100, rounded by caller
  isCorrection: boolean        // member.ts already computes this
  previousCorrectAnswers: number | null
}

export interface RewardLedgerEntry {
  rewardType: string
  xpDelta: number
}

export interface CompletedQuestSummary {
  id: string
  code: string
  title: string
  xpAwarded: number
}

export interface UnlockedAchievementSummary {
  id: string
  code: string
  title: string
  iconKey: string | null
  xpAwarded: number
}

export interface ProcessScoreResult {
  xpEarned: number
  ledgerEntries: RewardLedgerEntry[]
  profile: ProfileSnapshot
  levelUp: { previousLevel: number; currentLevel: number; tier: LevelTier } | null
  streak: StreakState
  completedQuests: CompletedQuestSummary[]
  unlockedAchievements: UnlockedAchievementSummary[]
}

// XP constants (subject to tuning when Plan 6 admin lands)
const XP_QUIZ_COMPLETION = 25
const XP_SCORE_IMPROVED = 10
const XP_HIGH_SCORE = 15
const XP_PERFECT_SCORE = 25
const HIGH_SCORE_THRESHOLD = 80

function wibDateString(now: Date): string {
  // Plan 0 locked WIB everywhere. event_date and last_activity_date are
  // DATE columns; we emit the WIB calendar day as YYYY-MM-DD.
  const HOUR_MS = 60 * 60 * 1000
  const wibShifted = new Date(now.getTime() + 7 * HOUR_MS)
  const year = wibShifted.getUTCFullYear()
  const month = String(wibShifted.getUTCMonth() + 1).padStart(2, '0')
  const day = String(wibShifted.getUTCDate()).padStart(2, '0')
  return `${year}-${month}-${day}`
}

// Imports below are local to the orchestrator; ensureProfile must run
// before streak or quest work since both read the profile row.
import { ensureProfile } from './profileUpdater.js'

async function emitAndEvaluate(
  client: PoolClient,
  today: string,
  input: ProcessScoreInput,
  eventType: EventType,
  currentStreakDays: number,
  metadata?: Record<string, unknown>,
): Promise<QuestProgressResult[]> {
  await emitEvent(client, {
    childId: input.childId,
    eventType,
    sourceType: 'score_attempt',
    sourceId: input.scoreAttemptId,
    eventDate: today,
    metadata,
  })
  return evaluateForEvent(client, today, {
    childId: input.childId,
    eventType,
    eventSourceType: 'score_attempt',
    eventSourceId: input.scoreAttemptId,
    videoSubjectId: input.videoSubjectId,
    currentStreakDays,
  })
}

export async function processScoreSubmission(
  client: PoolClient,
  input: ProcessScoreInput,
): Promise<ProcessScoreResult> {
  const eventDate = wibDateString(new Date())
  const ledgerEntries: RewardLedgerEntry[] = []
  const allQuestResults: QuestProgressResult[] = []
  let totalDelta = 0

  // Step 1: ensure profile + advance streak. Streak uses pre-submission
  // state (last_activity_date) so it must run before the quest evaluator
  // (which reads current_streak_days for the streak-keeper quest).
  await ensureProfile(client, input.childId)
  const streak = await updateStreakForActivity(client, input.childId, eventDate)

  // Step 2: ensure today's quest slots exist. Idempotent — cheap if quests
  // were already generated by a dashboard hit earlier today.
  await ensureTodaysQuests(client, input.childId, eventDate)

  // Step 3: emit events + evaluate quests for each one. Order matters
  // because the post-quiz reward summary (Plan 4 UI) displays in
  // priority order: completion → high → perfect → improvement.
  const baseQuestResults = await emitAndEvaluate(
    client,
    eventDate,
    input,
    'QUIZ_SCORE_SUBMITTED',
    streak.currentStreakDays,
    {
      videoId: input.videoId,
      correctAnswers: input.correctAnswers,
      totalQuestions: input.totalQuestions,
      scorePercentage: input.scorePercentage,
      isCorrection: input.isCorrection,
    },
  )
  allQuestResults.push(...baseQuestResults)

  // First-time completion path. Decision D2: corrections do not re-grant
  // completion XP.
  if (!input.isCorrection) {
    const firstCompleteResults = await emitAndEvaluate(
      client,
      eventDate,
      input,
      'VIDEO_FIRST_COMPLETED',
      streak.currentStreakDays,
      { videoId: input.videoId },
    )
    allQuestResults.push(...firstCompleteResults)

    const completion = await appendLedger(client, {
      childId: input.childId,
      rewardType: 'QUIZ_COMPLETION_XP',
      sourceType: 'score_attempt',
      sourceId: input.scoreAttemptId,
      xpDelta: XP_QUIZ_COMPLETION,
      metadata: { videoId: input.videoId },
    })
    if (completion.appended) {
      totalDelta += completion.xpDelta
      ledgerEntries.push({ rewardType: 'QUIZ_COMPLETION_XP', xpDelta: completion.xpDelta })
    }

    if (input.scorePercentage === 100) {
      const perfectQuestResults = await emitAndEvaluate(
        client, eventDate, input, 'PERFECT_SCORE_REACHED', streak.currentStreakDays,
      )
      allQuestResults.push(...perfectQuestResults)
      const perfect = await appendLedger(client, {
        childId: input.childId,
        rewardType: 'PERFECT_SCORE_XP',
        sourceType: 'score_attempt',
        sourceId: input.scoreAttemptId,
        xpDelta: XP_PERFECT_SCORE,
      })
      if (perfect.appended) {
        totalDelta += perfect.xpDelta
        ledgerEntries.push({ rewardType: 'PERFECT_SCORE_XP', xpDelta: perfect.xpDelta })
      }
    } else if (input.scorePercentage >= HIGH_SCORE_THRESHOLD) {
      const highQuestResults = await emitAndEvaluate(
        client, eventDate, input, 'HIGH_SCORE_REACHED', streak.currentStreakDays,
      )
      allQuestResults.push(...highQuestResults)
      const high = await appendLedger(client, {
        childId: input.childId,
        rewardType: 'HIGH_SCORE_XP',
        sourceType: 'score_attempt',
        sourceId: input.scoreAttemptId,
        xpDelta: XP_HIGH_SCORE,
      })
      if (high.appended) {
        totalDelta += high.xpDelta
        ledgerEntries.push({ rewardType: 'HIGH_SCORE_XP', xpDelta: high.xpDelta })
      }
    }
  } else {
    // Correction path: SCORE_IMPROVED fires iff new correct > previous best.
    const prior = input.previousCorrectAnswers ?? -1
    if (input.correctAnswers > prior) {
      const improvedQuestResults = await emitAndEvaluate(
        client, eventDate, input, 'SCORE_IMPROVED', streak.currentStreakDays,
        { videoId: input.videoId, previous: prior, current: input.correctAnswers },
      )
      allQuestResults.push(...improvedQuestResults)
      const improved = await appendLedger(client, {
        childId: input.childId,
        rewardType: 'SCORE_IMPROVED_XP',
        sourceType: 'score_attempt',
        sourceId: input.scoreAttemptId,
        xpDelta: XP_SCORE_IMPROVED,
        metadata: { previous: prior, current: input.correctAnswers },
      })
      if (improved.appended) {
        totalDelta += improved.xpDelta
        ledgerEntries.push({ rewardType: 'SCORE_IMPROVED_XP', xpDelta: improved.xpDelta })
      }
    }
  }

  // Step 4: sum quest XP into the total delta. Deduplicate quest results
  // by quest id (each event may match multiple quests, but a quest can
  // only complete once per window — appendLedger inside questEvaluator
  // already enforces idempotency on the ledger row).
  const completedById = new Map<string, QuestProgressResult>()
  for (const q of allQuestResults) {
    if (q.justCompleted && !completedById.has(q.questId)) {
      completedById.set(q.questId, q)
    }
  }
  const completedQuests: CompletedQuestSummary[] = []
  for (const q of completedById.values()) {
    totalDelta += q.xpAwarded
    if (q.xpAwarded > 0) {
      ledgerEntries.push({ rewardType: 'DAILY_QUEST_XP', xpDelta: q.xpAwarded })
    }
    completedQuests.push({
      id: q.questId,
      code: q.code,
      title: q.title,
      xpAwarded: q.xpAwarded,
    })
  }

  // Step 5: evaluate achievements. Runs after quests so that the
  // post-submission state (badges, unlocks, events, streak) is fully
  // applied before predicates are checked.
  const newAchievements: UnlockedAchievement[] = await evaluateAchievements(
    client,
    input.childId,
    streak,
  )
  const unlockedAchievements: UnlockedAchievementSummary[] = []
  for (const ach of newAchievements) {
    totalDelta += ach.xpAwarded
    if (ach.xpAwarded > 0) {
      ledgerEntries.push({ rewardType: 'ACHIEVEMENT_XP', xpDelta: ach.xpAwarded })
    }
    unlockedAchievements.push({
      id: ach.id,
      code: ach.code,
      title: ach.title,
      iconKey: ach.iconKey,
      xpAwarded: ach.xpAwarded,
    })
  }

  // Step 6: atomic profile delta. Single UPDATE, race-safe (eng review F1).
  const profileResult = await updateProfileWithDelta(client, {
    childId: input.childId,
    xpDelta: totalDelta,
    activityDate: eventDate,
  })

  return {
    xpEarned: totalDelta,
    ledgerEntries,
    profile: profileResult.after,
    levelUp: profileResult.levelUp,
    streak,
    completedQuests,
    unlockedAchievements,
  }
}
